### ISSUE TITLE
Error while running pug-adder 

### ISSUE THREAD

**Issue by killawabbit** [Leftium/pug-adder#1]
to reproduce error:
npx svelte-add Leftium/pug-adder
Need to install the following packages:
  svelte-add
Ok to proceed? (y) y
➕ Svelte Add (Version 2022.02.03.05)
node:internal/errors:464
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/home/fvkmedia/.npm/_npx/76ab19934dff27c3/node_modules/svelte-add/adders/Leftium/pug-adder/__info.js' imported from /home/fvkmedia/.npm/_npx/76ab19934dff27c3/node_modules/svelte-add/index.js
    at new NodeError (node:internal/errors:371:5)
    at finalizeResolution (node:internal/modules/esm/resolve:394:11)
    at moduleResolve (node:internal/modules/esm/resolve:944:10)
    at defaultResolve (node:internal/modules/esm/resolve:1041:11)
    at ESMLoader.resolve (node:internal/modules/esm/loader:530:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:251:18)
    at ESMLoader.import (node:internal/modules/esm/loader:332:22)
    at importModuleDynamically (node:internal/modules/esm/translators:106:35)
    at importModuleDynamicallyCallback (node:internal/process/esm_loader:35:14)
    at getAdderInfo (file:///home/fvkmedia/.npm/_npx/76ab19934dff27c3/node_modules/svelte-add/index.js:706:34) {
  code: 'ERR_MODULE_NOT_FOUND'
}

Node.js v17.4.0

and sure enough that folder or file doesn't exist. What is wrong?

**Comment by killawabbit** [comment]
BTW if you're interested I did a couple of useful stuff in my repo [killawabbit](https://github.com/killawabbit)/[svelte-pug-cs-styl](https://github.com/killawabbit/svelte-pug-cs-styl) such as VScode shortcut templates and a guide to the svelte-preprocessor pug mixins. Maybe its something you'd want to include?

**Comment by Leftium** [comment]
The Pug adder needs to be rewritten. The core Svelte Adder was rewritten, and doesn't use [Preset](https://preset.dev/) anymore.

A work-around may be to use Preset with the original Pug-adder preset.ts file like this:

    npx @preset/cli apply Leftium/pug-adder

However, note this may not be compatible with other Svelte Adders. One of the reasons the core Svelte Adder was rewritten was to allow different adders to work with each other better. I suggest running Svelte Adders last for maximum compatibility.


https://github.com/svelte-add/svelte-add#-external-integration-adders

**Comment by Leftium** [comment]
Here is a better workaround:
1.  Add coffeescript via the adder: `npx svelte-add@latest coffeescript`
2.  Add the pug module via npm: `npm add -D pug`
3. (Optionally: remove CoffeeScript-specific changes if don't need them.)

Why this works:
- CoffeeScript and Pug need similar modifications to the SvelteKit template project (i.e. adding svelte preprocessor)
- Pug is just missing the pug NPM module.
- Some more modification may be needed to get external pug files working, but I kept getting errors when trying  to add vite-plugin-pug manually.

Example:
- https://feh-shing-p00ekxjjg-leftium.vercel.app/
- https://github.com/Leftium/FEHshing/commit/dfae5358603eff27a26afd9c025de7fa2a62b0e3
- https://github.com/Leftium/FEHshing/commit/fb77b2bbb91040a927ccd486c87c62f88cf42823
- https://github.com/Leftium/FEHshing/commit/2267dcb7227007113b326042c5d30a502a2c46ca

**Comment by fredguth** [comment]
It didn't work for me, see (from a new sveltekit):
```
~/code/remotocare/newsite ❯ pnpm i                                                      Py base 07:20:15
Packages: +340
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: /Users/fredguth/.pnpm-store/v3
  Virtual store is at:             node_modules/.pnpm
Progress: resolved 359, reused 320, downloaded 20, added 340, done
node_modules/.pnpm/svelte-preprocess@4.10.5_svelte@3.47.0+typescript@4.6.3/node_modules/svelte-preprocesnode_modules/.pnpm/svelte-preprocess@4.10.5_svelte@3.47.0+typescript@4.6.3/node_modules/svelte-preprocess: Running postinstall script, done in 12ms
node_modules/.pnpm/esbuild@0.14.36/node_modules/esbuild: Running postinstall script, done in 56ms

> newsite@0.0.1 prepare /Users/fredguth/Code/RemotoCare/newsite
> svelte-kit sync


devDependencies:
+ @playwright/test 1.21.0
+ @sveltejs/adapter-auto 1.0.0-next.34
+ @sveltejs/kit 1.0.0-next.311
+ @typescript-eslint/eslint-plugin 5.19.0
+ @typescript-eslint/parser 5.19.0
+ eslint 7.32.0 (8.13.0 is available)
+ eslint-config-prettier 8.5.0
+ eslint-plugin-svelte3 3.4.1
+ prettier 2.6.2
+ prettier-plugin-svelte 2.7.0
+ svelte 3.47.0
+ svelte-check 2.6.0
+ svelte-preprocess 4.10.5
+ tslib 2.3.1
+ typescript 4.6.3
~/code/remotocare/newsite ❯ npx svelte-add Leftium/pug-adder                        17s Py base 07:20:36
➕ Svelte Add (Version 2022.04.06.01)
node:internal/errors:464
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Users/fredguth/.npm/_npx/76ab19934dff27c3/node_modules/svelte-add/adders/Leftium/pug-adder/__info.js' imported from /Users/fredguth/.npm/_npx/76ab19934dff27c3/node_modules/svelte-add/index.js
    at new NodeError (node:internal/errors:371:5)
    at finalizeResolution (node:internal/modules/esm/resolve:418:11)
    at moduleResolve (node:internal/modules/esm/resolve:983:10)
    at defaultResolve (node:internal/modules/esm/resolve:1080:11)
    at ESMLoader.resolve (node:internal/modules/esm/loader:530:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:251:18)
    at ESMLoader.import (node:internal/modules/esm/loader:332:22)
    at importModuleDynamically (node:internal/modules/esm/translators:106:35)
    at importModuleDynamicallyCallback (node:internal/process/esm_loader:35:14)
    at getAdderInfo (file:///Users/fredguth/.npm/_npx/76ab19934dff27c3/node_modules/svelte-add/index.js:706:34) {
  code: 'ERR_MODULE_NOT_FOUND'
}
~/code/remotocare/newsite ❯ npx svelte-add@latest tailwindcss                           Py base 07:20:54
➕ Svelte Add (Version 2022.04.06.01)
The project directory you're giving to this command cannot be determined to be guaranteed fresh — maybe it is, maybe it isn't. If any issues arise after running this command, please try again, making sure you've run it on a freshly initialized SvelteKit or Vite–Svelte app template.

PostCSS
 ✅ successfully set up and repaired (it looks like it was in a broken setup before this command was run)!
Create or find an existing issue at https://github.com/svelte-add/svelte-add/issues if this is wrong.

Tailwind CSS
 ✅ successfully set up!
Create or find an existing issue at https://github.com/svelte-add/svelte-add/issues if this is wrong.

Run pnpm install to install new dependencies, and then reload your IDE before starting your app.
~/code/remotocare/newsite ❯ npx svelte-add@latest Leftium/pug-adder                     Py base 07:21:44
➕ Svelte Add (Version 2022.04.06.01)
node:internal/errors:464
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Users/fredguth/.npm/_npx/583905104f230c6e/node_modules/svelte-add/adders/Leftium/pug-adder/__info.js' imported from /Users/fredguth/.npm/_npx/583905104f230c6e/node_modules/svelte-add/index.js
    at new NodeError (node:internal/errors:371:5)
    at finalizeResolution (node:internal/modules/esm/resolve:418:11)
    at moduleResolve (node:internal/modules/esm/resolve:983:10)
    at defaultResolve (node:internal/modules/esm/resolve:1080:11)
    at ESMLoader.resolve (node:internal/modules/esm/loader:530:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:251:18)
    at ESMLoader.import (node:internal/modules/esm/loader:332:22)
    at importModuleDynamically (node:internal/modules/esm/translators:106:35)
    at importModuleDynamicallyCallback (node:internal/process/esm_loader:35:14)
    at getAdderInfo (file:///Users/fredguth/.npm/_npx/583905104f230c6e/node_modules/svelte-add/index.js:706:34) {
  code: 'ERR_MODULE_NOT_FOUND'
}
~/code/remotocare/newsite ❯ npx svelte-add@latest coffeescript                          Py base 07:21:55
➕ Svelte Add (Version 2022.04.06.01)
The project directory you're giving to this command cannot be determined to be guaranteed fresh — maybe it is, maybe it isn't. If any issues arise after running this command, please try again, making sure you've run it on a freshly initialized SvelteKit or Vite–Svelte app template.

CoffeeScript
 ✅ successfully set up!
Create or find an existing issue at https://github.com/svelte-add/svelte-add/issues if this is wrong.

Run pnpm install to install new dependencies, and then reload your IDE before starting your app.

~/code/remotocare/newsite ❯ pnpm i                                                      Py base 07:22:52
Packages: +35 -2
+++++++++++++++++++++++++++++++++++--
Progress: resolved 392, reused 363, downloaded 10, added 35, done
node_modules/.pnpm/svelte-preprocess@4.10.5_30e9af7e9cb86c397aa75ddf768a2659/node_modules/svelte-preprocnode_modules/.pnpm/svelte-preprocess@4.10.5_30e9af7e9cb86c397aa75ddf768a2659/node_modules/svelte-preprocess: Running postinstall script, done in 11ms

> newsite@0.0.1 prepare /Users/fredguth/Code/RemotoCare/newsite
> svelte-kit sync


devDependencies:
+ autoprefixer 10.4.4
+ coffeescript 2.6.1
+ postcss 8.4.12
+ postcss-load-config 3.1.4
- svelte-check 2.6.0
+ svelte-check 2.6.0
- svelte-preprocess 4.10.5
+ svelte-preprocess 4.10.5
+ tailwindcss 3.0.24
+ vite-plugin-coffee 2.2.1

~/code/remotocare/newsite ❯ npx svelte-add@latest Leftium/pug-adder                  6s Py base 07:25:02
➕ Svelte Add (Version 2022.04.06.01)
node:internal/errors:464
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Users/fredguth/.npm/_npx/583905104f230c6e/node_modules/svelte-add/adders/Leftium/pug-adder/__info.js' imported from /Users/fredguth/.npm/_npx/583905104f230c6e/node_modules/svelte-add/index.js
    at new NodeError (node:internal/errors:371:5)
    at finalizeResolution (node:internal/modules/esm/resolve:418:11)
    at moduleResolve (node:internal/modules/esm/resolve:983:10)
    at defaultResolve (node:internal/modules/esm/resolve:1080:11)
    at ESMLoader.resolve (node:internal/modules/esm/loader:530:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:251:18)
    at ESMLoader.import (node:internal/modules/esm/loader:332:22)
    at importModuleDynamically (node:internal/modules/esm/translators:106:35)
    at importModuleDynamicallyCallback (node:internal/process/esm_loader:35:14)
    at getAdderInfo (file:///Users/fredguth/.npm/_npx/583905104f230c6e/node_modules/svelte-add/index.js:706:34) {
  code: 'ERR_MODULE_NOT_FOUND'
}

```
